ll title: <p align="center"> Senthil Nathan </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/senthil-nathan-9a4bb540/">LinkedIn</a> |
  <a href="https://github.com/jsenathan">GitHub</a>
  
  <br>   
  I'm working on Cloud Architeture and developement.

  <br>
  </p>



theme: jekyll-theme-minimal
